{% set version = "3.2.2" %}

package:
  name: abacus
  version: {{ version }}

source:
  # path: ..
  git_url: https://github.com/deepmodeling/abacus-develop.git
  git_rev: v{{ version }}

build:
  skip: true  # [not linux]
  script: |
    export CMAKE_PREFIX_PATH=`python -c "import torch;print(torch.__path__[0])"`/share/cmake:$CMAKE_PREFIX_PATH
    cmake -B conda_build ${CMAKE_ARGS} -DCMAKE_BUILD_TYPE=Release -DENABLE_DEEPKS=1 -DENABLE_LIBXC=1
    cmake --build conda_build -j`nproc`
    cmake --install conda_build
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - cmake

  host:
    - {{ mpi }}
    - openblas=*=openmp*
    - elpa=*=mpi*
    - fftw=*=mpi*
    - cereal
    - pytorch
    - libxc

  run:
    - libopenblas=*=openmp*
    - scalapack
    - elpa=*=mpi*
    - fftw=*=mpi*

test:
  commands:
    - abacus
    - mpirun -n 2 abacus

about:
  home: http://abacus.ustc.edu.cn/
  doc_url: https://abacus.deepmodeling.com/
  dev_url: https://github.com/deepmodeling/abacus-develop
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: An electronic structure package based on plane wave and numerical atomic basis sets.
  description: >
    ABACUS (Atomic-orbital Based Ab-initio Computation at UStc) is an open-source package based on density functional theory (DFT).
    The package utilizes both plane wave and numerical atomic basis sets with the usage of norm-conserving pseudopotentials
    to describe the interactions between nuclear ions and valence electrons. ABACUS supports LDA, GGA, meta-GGA, and hybrid functionals.
    Apart from single-point calculations, the package allows geometry optimizations and ab-initio molecular dynamics with various ensembles.

extra:
  recipe-maintainers:
    - caic99
